### PR TITLE
Fix consistency of printed messages using Ui class.

### LINKED ISSUE #132: [PE-D] Wrong warning prompt for invalid date input
Perhaps the warning should not be wrong format but invalid date.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zsk612/ped#2

### LINKED ISSUE #149: [PE-D] Error Message is Wrong
The wrong error message is given beacause it is a correct command

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: shikai-zhou/ped#2

### LINKED ISSUE #157: [PE-D] The examples provided does not distinguish between user input and application output
I believe that separating the user's input and the application output will make the readers of the UG understand the program better as it reduces confusion. Currently, it is in the same code block and a not-so-tech-savvy person(e.g. a CEG freshman without prior technical experience) might not understand what was typed into the program.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: e0426051/ped#4

### PR DESCRIPTION
**Pull request by daniellimzj**
Ensures correct error messages are printed. Fixes #149 and fixes #132 .
Ensures clearer distinction between the type of messages being printed, as well as user's input. Fixes #157 .

### CODE REVIEW

File: src/main/java/seedu/lifeasier/commands/HelpCommand.java [hunk 1]
```diff
@@ -22,6 +22,6 @@
     @Override
     public void execute(Ui ui, NoteList notes, TaskList tasks, FileStorage storage, Parser parser,
                         NoteHistory noteHistory, TaskHistory taskHistory) {
-        ui.showHelp();
+        ui.showHelpMessage();
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/commands/HelpCommand.java]: Maybe this would sound nicer, but i'm not sure if it will fit the current style you are going for.

```suggestion
        ui.showHelpMenu();
```

**Review by dojh111 — COMMENTED** [review]
Looks good to me! Really like how the messages are split into error, prompt and message types.

File: src/main/java/seedu/lifeasier/commands/HelpCommand.java (hunk 1 above)
Comment (daniellimzj) [reply src/main/java/seedu/lifeasier/commands/HelpCommand.java]: I guess it's fine! Help is kind of an exception to the normal messages anyway.
