### PR TITLE
Fix delete out of bounds note

### LINKED ISSUE #147: [PE-D] deleteNotes can delete out of scope
Similar to how editLesson/Deadline/Event and deleteTask can delete outside a specific type, notes not searched can be deleted too. Although it is good that you can look at the note before you can delete it, which can also be done for the tasks, it is better to send an error message. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jessicazhang617/ped#8

### PR DESCRIPTION
**Pull request by EdmundEXE**
User cannot input a number that is not from the list shown. This applies to showNotes and editNotes as well. Fixes #147 .

### CODE REVIEW

File: src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java [hunk 1]
```diff
@@ -20,14 +20,15 @@
...
+    private int arraySize = 10000;
 
     public DeleteNotesCommand(String title) {
         this.title = title;
     }
 
     private void findTitle(Ui ui, NoteList notes, String title, NoteHistory noteHistory) throws TitleNotFoundException {
         logger.log(Level.INFO, "Start for finding title in note list");
-
+        int[] matchArr = new int [arraySize];
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java]: You might want to consider a new name for the array. Maybe something like "noteMatches"?

File: src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java [hunk 2]
```diff
@@ -49,16 +50,16 @@ private void findTitle(Ui ui, NoteList notes, String title, NoteHistory noteHist
             ui.showMultipleMatchesFoundMessage();
 
             logger.log(Level.INFO, "Start of printing all matching notes");
-            ui.printMultipleNoteMatches(notes, title);
+            matchArr = ui.printMultipleNoteMatches(notes, title, matchArr);
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java]: Maybe you can try revamp this to use an ArrayList instead of Array. If it's too much then it's ok

**Review by dojh111 — COMMENTED** [review]
Minor changes, otherwise looks good

File: src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java [hunk 3]
```diff
@@ -49,16 +50,16 @@ private void findTitle(Ui ui, NoteList notes, String title, NoteHistory noteHist
...
             logger.log(Level.INFO, "End of printing all matching notes");
 
             noteNumber = Integer.parseInt(ui.readCommand());
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/commands/DeleteNotesCommand.java]: Would you consider adding the "-1" logic in this line instead of in all the other times you use noteNumber?
```suggestion
            noteNumber = Integer.parseInt(ui.readCommand()) - 1;
```

File: src/main/java/seedu/lifeasier/commands/EditNotesCommand.java [hunk 4]
```diff
@@ -48,16 +49,16 @@ private void findTitle(Ui ui, NoteList notes, Parser parser,
             ui.showMultipleMatchesFoundMessage();
 
             logger.log(Level.INFO, "Start of printing all matching notes");
-            ui.printMultipleNoteMatches(notes, title);
+            matchArr = ui.printMultipleNoteMatches(notes, title, matchArr);
             logger.log(Level.INFO, "End of printing all matching notes");
 
-            noteNumber = Integer.parseInt(ui.readCommand()) - 1;
-            NoteCommandFunctions.checkForIndexOutOfBounds(notes, noteNumber);
+            noteNumber = Integer.parseInt(ui.readCommand());
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/commands/EditNotesCommand.java]: Same comment about the "-1" logic. I'm not sure if that'll help to make it clearer!

**Review by daniellimzj — COMMENTED** [review]
Looks good! I agree with Danzel's comments as well.
