### PR TITLE
Fix indexing error for delete and edit commands

### LINKED ISSUE #162: [PE-D] For editting events allows for an empty title/description
This results in affecting the entire functionalty of the program, as now even though the user cannot see in their schedule, they are occupied from time slots as mentioned in the event. 

It results in something like this when `display` command is executed.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: gmit22/ped#5

### PR DESCRIPTION
**Pull request by skyaxe97**
Fixes #162 #139 #113

### CODE REVIEW

File: src/main/java/seedu/lifeasier/model/tasks/TaskList.java [hunk 1]
```diff
@@ -22,7 +23,8 @@
 
     private static Logger logger = Logger.getLogger(ShowNotesCommand.class.getName());
     protected static ArrayList<Task> taskList;
-    private int indexOfLastMatch;
+    private int displayIndexOfLastMatch = 0;
+    HashMap<Integer,Integer> map;
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/model/tasks/TaskList.java]: Wow nice use of a hashmap. However, could the name be made more descriptive?

**Review by daniellimzj — COMMENTED** [review]
Generally looks good! Just one small thing!

File: src/main/java/seedu/lifeasier/model/tasks/TaskList.java (hunk 1 above)
Comment (dojh111) [reply src/main/java/seedu/lifeasier/model/tasks/TaskList.java]: Maybe something like `taskMap`
