### PR TITLE
Bug Fixing and UGDG updates for v2.1

### LINKED ISSUE #125: [PE-D] No support for clashing items on the time table
No details provided.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: snowbanana12345/ped#5

### LINKED ISSUE #129: [PE-D] Why is this colored teal?
No details provided.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: snowbanana12345/ped#9

### LINKED ISSUE #159: [PE-D] Legitimate user behavior is not handled : Extra parameters
May I suggest using/ accepting additional parameters other than `display week` or handling the additional parameters mentioned by the user.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: gmit22/ped#2

### PR DESCRIPTION
**Pull request by johan9se**
Ensures extra params are not accepted for display command. Fixes #159 .
Prints description message regarding coloured curr hour in timetable. Fixes #129 .
UG updated to state that there is no warning regarding clashing tasks. Fixes #125 .

### CODE REVIEW

File: src/main/java/seedu/lifeasier/parser/Parser.java [hunk 1]
```diff
@@ -512,14 +512,46 @@ private Command parseEditNotesCommand(String input) {
      * @param input String containing the user's input.
      * @return DisplayScheduleCommand with the parameters input by the user.
      */
-    private Command parseDisplayScheduleCommand(String input) {
-
+    private Command parseDisplayScheduleCommand(String input) throws ParserException {
+        Ui ui = new Ui();
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/parser/Parser.java]: Can we find a way to do it without instantiating another Ui object? I think that when we call parseCommand from LifEasier, we already pass in a Ui object.

File: src/main/java/seedu/lifeasier/ui/Ui.java [hunk 2]
```diff
@@ -582,4 +582,20 @@ public void showInvalidRecurrencesError() {
...
+
+    public void showEnterDisplayKeywordMessage() {
+        System.out.println(colourTextCyan("To see your schedule, please enter: ") + "week/today/tomorrow");
+        printSeparator();
+    }
+
+    public void showInvalidDisplayKeyword() {
+        System.out.println("Invalid display parameter! Try 'week', 'today' or 'tomorrow' instead!");
+        printSeparator();
+    }
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/ui/Ui.java]: I think that since it is an error, you could consider naming it as such, and printing it in red.
```suggestion
    public void showInvalidDisplayKeywordError() {
        System.out.println(colourTextRed("Invalid display parameter! Try 'week', 'today' or 'tomorrow' instead!"));
        printSeparator();
    }```

**Review by daniellimzj — COMMENTED** [review]
Looks great! Just a few tiny issues

File: src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java [hunk 3]
```diff
@@ -2,42 +2,53 @@
...
+            scheduleUi.showHome(tasks, ui);
+            break;
+        case "today":
+            displayScheduleFor(currDate, tasks, ui);
+            break;
+        case "tomorrow":
+            displayScheduleFor(currDate.plus(1, ChronoUnit.DAYS), tasks, ui);
+            break;
+        default:
+            ui.showInvalidDisplayKeyword();
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/commands/DisplayScheduleCommand.java]: Can rename this to match Daniel's naming style
```suggestion
            ui.showInvalidDisplayKeywordError();
```

**Review by dojh111 — COMMENTED** [review]
Lgtm, only minor errors!
