### PR TITLE
Fix bug causing save file to not be read when new save created

### LINKED ISSUE #57: Save reading function does not read from existing files after creating new files
When new save files are created, the save reading function does not read the contents of the other existing save file, thus resulting in save data not being read.

### PR DESCRIPTION
**Pull request by dojh111**
Fixes #57

### CODE REVIEW

File: src/main/java/seedu/lifeasier/storage/FileStorage.java [hunk 1]
```diff
@@ -94,15 +94,21 @@ private void checkForNotesSaveFile(File saveFileNotes) {
         //Create new save file if task save file does not exist
         if (!saveFileNotes.exists()) {
             createNewSaveFile(saveFileNotes);
+            return;
         }
+        //Read note save file
+        noteStorage.readNotesSave(filePathNotes);
     }
 
     private void checkForTaskSaveFile(File saveFileTasks) {
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/storage/FileStorage.java]: Could be renamed to make it consistent with checkForNotesSaveFile and other variables
```suggestion
    private void checkForTasksSaveFile(File saveFileTasks) {
```

**Review by daniellimzj — COMMENTED** [review]
Just one small issue!
