### PR TITLE
Fix lesson updates and duplicates

### LINKED ISSUE #130: [PE-D] No handling of duplicate deadlines
No details provided.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: snowbanana12345/ped#10

### LINKED ISSUE #144: [PE-D] No Lesson shown in timetable
There is no lesson shown in the timetable although both lessons should repeat for 30 times weekly.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jessicazhang617/ped#5

### PR DESCRIPTION
**Pull request by daniellimzj**
Updates tasks when they are first added. Fixes #144 .
Does not allow duplicates or similar tasks. Fixes #130

### CODE REVIEW

File: src/main/java/seedu/lifeasier/commands/AddEventCommand.java [hunk 1]
```diff
@@ -33,11 +37,23 @@ public AddEventCommand(String description, LocalDateTime start, LocalDateTime en
...
-        storage.saveTasks();
-        ui.showAddConfirmationMessage(task);
+        try {
+            logger.log(Level.INFO, "Adding event to taskList...");
+            Task task = tasks.addEvent(description, start, end, recurrences);
+            tasks.updateTasks(LocalDate.now());
+            ui.showAddConfirmationMessage(task);
+            logger.log(Level.INFO, "Saving updated taskList to storage...");
+            storage.saveTasks();
+
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/commands/AddEventCommand.java:59]: Random white space

File: src/main/java/seedu/lifeasier/model/tasks/Deadline.java [hunk 2]
```diff
@@ -70,6 +72,19 @@ public void moveAndUpdateRecurrences(LocalDate day) {
...
+        LocalTime existingBy = this.by.toLocalTime();
+        DayOfWeek existingDay = this.by.getDayOfWeek();
+
+        LocalTime newBy = by.toLocalTime();
+        DayOfWeek newDay = by.getDayOfWeek();
 
+        return (this.description.equals(description)
+                && existingBy == newBy
+                && existingDay == newDay
+                && ((this.recurrences > 0 && recurrences > 0) || this.by.equals(by)));
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/model/tasks/Deadline.java:97]: Maybe we can focus on readability more for this part instead of valuing performance, so we can change this to a boolean value and return it instead. 
```suggestion
       boolean isDuplicate = (this.description.equals(description)
                && existingBy == newBy
                && existingDay == newDay
                && ((this.recurrences > 0 && recurrences > 0) || this.by.equals(by)));
      return isDuplicate;
```

File: src/main/java/seedu/lifeasier/model/tasks/Event.java [hunk 3]
```diff
@@ -73,4 +75,21 @@ public void moveAndUpdateRecurrences(LocalDate day) {
...
+
+        LocalTime newStartTime = start.toLocalTime();
+        LocalTime newEndTime = end.toLocalTime();
+        DayOfWeek newDay = start.getDayOfWeek();
+
+        return (this.description.equals(description)
+                && existingStartTime == newStartTime
+                && existingEndTime == newEndTime
+                && existingDay == newDay
+                && ((this.recurrences > 0 && recurrences > 0) || this.start.equals(start)));
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/model/tasks/Event.java:103]: Since this whole part is similar to lesson, maybe it can be factored out to be a common method to reduce duplicated code.

File: src/main/java/seedu/lifeasier/ui/Ui.java [hunk 4]
```diff
@@ -582,4 +582,12 @@ public void showInvalidRecurrencesError() {
...
         printSeparator();
     }
+
+    public void showDuplicateTaskError(String type) {
+        System.out.println("This " + type + " or something very similar already exists in your schedule!");
+    }
+
+    public void showPastTaskError(String type) {
+        System.out.println("The timing of this " + type + " is already in the past!");
+    }
```
Comment (dojh111) [inline src/main/java/seedu/lifeasier/ui/Ui.java:682]: You might want to color these red

**Review by dojh111 — COMMENTED** [review]
Only minor issues, otherwise looks pretty good!

File: src/main/java/seedu/lifeasier/ui/Ui.java (hunk 4 above)
Comment (daniellimzj) [reply src/main/java/seedu/lifeasier/ui/Ui.java:682]: I wanted to wait until we merged my other commits, so that I can add the blank lines and separators too. Thanks for pointing it out though!

File: src/main/java/seedu/lifeasier/model/tasks/Event.java (hunk 3 above)
Comment (daniellimzj) [reply src/main/java/seedu/lifeasier/model/tasks/Event.java:103]: I was thinking the same, but I was worried it would reduce the OOP aspect. I wanted to make this method inherit from Task, but couldn't because Deadlines don't store both the start and end times, but only the by.

File: src/main/java/seedu/lifeasier/model/tasks/Deadline.java (hunk 2 above)
Comment (daniellimzj) [reply src/main/java/seedu/lifeasier/model/tasks/Deadline.java:97]: Doing that causes IntelliJ to give me a warning that the boolean is unnecessary. I'll add a Javadoc comment instead to better explain what is happening. I hope that's sufficient!
