### PR TITLE
Change all /time to /from

### LINKED ISSUE #152: [PE-D] Cannot Add Lesson
For some reason this fails.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: shikai-zhou/ped#5

### PR DESCRIPTION
**Pull request by skyaxe97**
Fixes #152 
Also modified code to use static parameter strings

### CODE REVIEW

File: src/main/java/seedu/lifeasier/parser/Parser.java [hunk 1]
```diff
@@ -54,7 +54,7 @@
 
     public static final String PARAM_CODE = "/code";
     public static final String PARAM_DATE = "/date";
-    public static final String PARAM_TIME = "/time";
+    public static final String PARAM_TIME = "/from";
```
Comment (daniellimzj) [inline src/main/java/seedu/lifeasier/parser/Parser.java]: Could you consider renaming the parameter too?
```suggestion
    public static final String PARAM_FROM = "/from";
```

**Review by daniellimzj — COMMENTED** [review]
Just one tiny thing! Looks good otherwise!
